kafka:
  bootstrapServers: "localhost:29092"
  groupId: "scheduler-group"
  enableAutoCommit: false

  keySerializer: "org.apache.kafka.common.serialization.StringSerializer"
  valueSerializer: "org.apache.kafka.common.serialization.StringSerializer"
  keyDeserializer: "org.apache.kafka.common.serialization.StringDeserializer"
  valueDeserializer: "org.apache.kafka.common.serialization.StringDeserializer"

  acks: "all"
  retries: 3
  requestTimeoutMs: 30000
  batchSize: 16384
  lingerMs: 5
  bufferMemory: 33554432
